[package]
name = "metrics-sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
prometheus = "0.13"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.10"
actix-web = "4.4"
regex = "1.5"