services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - metrics-network

  main-app:
    build: ./main-app
    ports:
      - "8080:8080"
    networks:
      - metrics-network
    depends_on:
      - sidecar

  sidecar:
    build: ./sidecar
    ports:
      - "9091:9091"
      - "9092:9092/udp"
    networks:
      - metrics-network

networks:
  metrics-network:
    driver: bridge